-- AlterTable
ALTER TABLE `medicalcase` MODIFY `chiefComplaint` VARCHAR(255) NULL,
    MODIFY `status` ENUM('PENDING_REVIEW', 'IN_TREATMENT', 'REFERRED', 'CLOSED') NOT NULL DEFAULT 'PENDING_REVIEW';

-- AlterTable
ALTER TABLE `medicalimage` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `isQcPassed` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `patient` ADD COLUMN `birthDate` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `referral` ADD COLUMN `callbackOpinion` TEXT NULL,
    MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'ACCEPTED', 'REJECTED', 'COMPLETED') NOT NULL DEFAULT 'PENDING';
