-- AlterTable
ALTER TABLE `approvalrecord` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `type` ENUM('PROJECT_REGISTRATION', 'EXPORT_REQUEST', 'CONSULTATION_REQUEST', 'ROLE_CHANGE', 'ANONYMIZATION_QC') NOT NULL;

-- AlterTable
ALTER TABLE `auditlog` ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user` ADD COLUMN `accountStatus` ENUM('ENABLED', 'PENDING', 'DISABLED') NOT NULL DEFAULT 'ENABLED';
