/** 与 prisma UserRole 对齐 */
export const USER_ROLES = Object.freeze({
  DOCTOR: 'DOCTOR',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  RESEARCH_ADMIN: 'RESEARCH_ADMIN',
  SECURITY_ADMIN: 'SECURITY_ADMIN',
})

export const ADMIN_LIKE_ROLES = Object.freeze([
  USER_ROLES.HOSPITAL_ADMIN,
  USER_ROLES.RESEARCH_ADMIN,
  USER_ROLES.SECURITY_ADMIN,
])
